line-length = 121
indent-width = 4

target-version = "py310"

[lint]
# Default `select`: ["E4", "E7", "E9", "F"]
extend-select = [
    "E501",
    "UP",
    "C90",
    "N81",
    "N999",
    "YTT",
    "ANN001",
    "S",
    "BLE",
    "FBT",
    "B",
    "A",
    "COM818",
    "COM819",
    "T10",
    "EM",
    "EXE",
    "FA",
    "ISC",
    "ICN",
    "INP",
    "PIE",
    "PYI",
    "RSE",
    "RET503",
    "SIM",
    "TC",
    "PTH",
    "PL",
    "PLW",
    "NPY",
    "PERF",
    "FURB",
    "RUF",
]

extend-ignore = [
    "E701",
]

[format]
indent-style = "space"

[analyze]
detect-string-imports = true